services:
  # Сервис Базы Данных
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=barber_db
      - POSTGRES_USER=barber_user
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"

  # Сервис Django (Сайт)
  web:
    build: .
    command: gunicorn --chdir web web.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./web/media:/app/web/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  # Сервис Бота
  bot:
    build: .
    command: python barberBot/main.py
    volumes:
      # 👇 ДОБАВЛЯЕМ ЭТУ СТРОКУ (пробрасываем весь проект внутрь контейнера)
      - .:/app
      # Оставляем твой лог (хотя он теперь дублируется, но пусть будет для явности)
      - ./bot_logs.txt:/app/bot_logs.txt
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis

  # Сервис Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    working_dir: /app/web
    command: celery -A web worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - TZ=Europe/Kyiv
    depends_on:
      - web
      - db
      - redis

volumes:
  postgres_data: