# Generated by Django 6.0 on 2026-01-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_telegramuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUser',
            new_name='TelegramUsers',
        ),
    ]
