# Generated by Django 6.0 on 2026-01-27 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_telegramuser_telegramusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.telegramusers')),
            ],
        ),
    ]
