# Generated by Django 6.0 on 2026-01-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_appointmen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointmen',
            new_name='Appointment',
        ),
    ]
