# Generated by Django 6.0 on 2026-01-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_appointmen_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='photo_id',
        ),
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='masters/'),
        ),
    ]
