# Generated by Django 6.0 on 2026-02-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_appointment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusers',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
