# Generated by Django 6.0 on 2026-02-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_telegramusers_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusers',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
