# Generated by Django 6.0 on 2026-02-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_telegramusers_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusers',
            name='first_name',
        ),
    ]
