# Generated by Django 6.0 on 2026-02-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_telegramusers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
