# Generated by Django 6.0 on 2026-02-08 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_telegramusers_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.master')),
            ],
        ),
    ]
