# Generated by Django 6.0 on 2026-02-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_dayoff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUsers',
            new_name='TelegramUser',
        ),
    ]
