# Generated by Django 6.0 on 2026-02-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_telegramusers_telegramuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
