# Generated by Django 6.0 on 2026-02-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_appointment_client_name_appointment_phone_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='booking',
            name='master',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='dayoff',
            options={'verbose_name': 'Выходной', 'verbose_name_plural': 'Выходные'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('master', 'date', 'time'), name='unique_master_slot'),
        ),
        migrations.AddConstraint(
            model_name='dayoff',
            constraint=models.UniqueConstraint(fields=('master', 'date'), name='unique_master_dayoff'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
