# Generated by Django 6.0 on 2026-03-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_booking_unique_together_remove_booking_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='color',
            field=models.CharField(default='#76a2b3', max_length=7),
        ),
    ]
