# Generated by Django 6.0 on 2026-04-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_master_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='ID аккаунта мастера в Телеграм для доступа к кабинету', null=True, verbose_name='Telegram ID мастера'),
        ),
    ]
