# Generated by Django 6.0 on 2026-04-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_master_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('welcome_text', models.TextField(blank=True, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Настройки салона',
                'verbose_name_plural': 'Настройки салона',
            },
        ),
    ]
