name: BarberBot Tests

# Запускать при каждом пуше
on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest # Поднимаем чистый виртуальный сервер на Убунту

    steps:
      # 1. Скачиваем твой код на сервер
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Так как у тебя в проекте есть переменные окружения,
      # создадим фейковый .env прямо на лету, чтобы докер не ругался при сборке
      - name: Create fake .env for testing
        run: |
          touch .env
          echo "TOKEN=test_token" >> .env
          echo "ADMIN_ID=123456" >> .env

      # 3. Поднимаем твои контейнеры и запускаем тесты
      - name: Run Tests in Docker
        run: |
          # Запускаем докер в фоновом режиме
          docker-compose up -d
          
          # Даем базе данных 5 секунд на то, чтобы проснуться
          sleep 5
          
          # Твоя любимая команда, но с флагом -T (т.к. на сервере нет реальной клавиатуры/терминала)
          docker-compose exec -T web python web/manage.py test shop